// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace code_with_the_pen
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidInkToolWindowPackageString = "e1c1ea71-d1a2-43b3-88df-f1646502e9ce";
        public const string guidInkToolWindowPackageCmdSetString = "a0437697-8a9e-478f-8f5e-4e9023b63264";
        public const string guidImagesString = "46b3cdf4-d0cf-45fd-b0ae-a79fdbe51cd5";
        public static Guid guidInkToolWindowPackage = new Guid(guidInkToolWindowPackageString);
        public static Guid guidInkToolWindowPackageCmdSet = new Guid(guidInkToolWindowPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int InkToolWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}
